title: I'm a man.
description: 関西在住の50代バツイチフリーエンジニアの日常を綴ります
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: ""
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: xstar03b
author-img: 
about-author: 
social-twitter: false
social-facebook: false
social-github: xstar03b
social-linkedin: false
social-email: false

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
